import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { getOctokit } from "@/lib/github/octokit";
import { logWorkStart, logWorkComplete, logWorkFailure } from "@/lib/db/dal";
import type { AuditReport } from "@/lib/types";

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.accessToken) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { report } = (await request.json()) as { report: AuditReport };

  if (!report || !report.repo) {
    return NextResponse.json({ error: "report is required" }, { status: 400 });
  }

  const [owner, repoName] = report.repo.split("/");
  if (!owner || !repoName) {
    return NextResponse.json({ error: "Invalid repo format" }, { status: 400 });
  }

  const workId = await logWorkStart(
    session.user?.email ?? undefined,
    "best-practices-audit",
    report.repo,
    `Create audit issue for ${report.repo}`
  );

  try {
    const octokit = getOctokit(session.accessToken);

    const passCount = report.checks.filter((c) => c.status === "pass").length;
    const failCount = report.checks.filter((c) => c.status === "fail").length;
    const warnCount = report.checks.filter((c) => c.status === "warning").length;

    const checksTable = report.checks
      .map((c) => {
        const icon = c.status === "pass" ? ":white_check_mark:" : c.status === "fail" ? ":x:" : ":warning:";
        return `| ${icon} ${c.status.toUpperCase()} | ${c.name} | ${c.description} |`;
      })
      .join("\n");

    const recommendations = report.recommendations
      .map((rec) => `- [ ] ${rec}`)
      .join("\n");

    const body = [
      `## Best Practices Audit Report`,
      "",
      `**Repository:** ${report.repo}`,
      `**Compliance Score:** ${report.complianceScore}%`,
      `**Date:** ${report.createdAt}`,
      "",
      `### Summary`,
      "",
      `| Passed | Failed | Warnings |`,
      `|--------|--------|----------|`,
      `| ${passCount} | ${failCount} | ${warnCount} |`,
      "",
      `### Checks`,
      "",
      `| Status | Check | Details |`,
      `|--------|-------|---------|`,
      checksTable,
      "",
      `### Recommendations`,
      "",
      recommendations,
      "",
      "---",
      "*Generated by [Repo-Ninja](https://github.com/Rickcau/Repo-Ninja) best practices audit*",
    ].join("\n");

    const { data } = await octokit.rest.issues.create({
      owner,
      repo: repoName,
      title: `[Audit] Best Practices Report — ${report.complianceScore}% compliance`,
      body,
      labels: ["audit", "best-practices"],
    });

    await logWorkComplete(workId, { issueNumber: data.number, issueUrl: data.html_url });

    return NextResponse.json({
      issueNumber: data.number,
      issueUrl: data.html_url,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    await logWorkFailure(workId, message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
